global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "portfolio-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["portfolio-api:8000"]
        labels:
          app: "portfolio-balancer"
